server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    cors:
      allowed-origins: "http://localhost:5173"
      allowed-methods: "*"
      allowed-headers: "*"

logging:
  level:
    com.resume: DEBUG
    org.springframework.web: DEBUG

app:
  upload:
    temp-dir: ${java.io.tmpdir}/resume-uploads
  templates:
    path: classpath:templates/
